version: "3.2"

services:
  py_app:
    image: att_app:1.6
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /vagrant/attendance_reports
        target: /github_actions_test/attendance_reports
      - type: bind
        source: /vagrant/attendance_reports_queries
        target: /github_actions_test/attendance_reports_queries
      - type: bind
        source: /vagrant/github_actions_test/coverage
        target: /github_actions_test/coverage
  
  py_app_tests:
    command: coverage run -m pytest
  
  py_app_coverage:
    command: coverage html