version: "3.2"

services:
  py_app:
    build:
    volumes:
      - type: bind
        source: /vagrant/attendance_reports
        target: /github_actions_test/attendance_reports
      - type: bind
        source: /vagrant/attendance_reports_queries
        target: /github_actions_test/attendance_reports_queries
      - type: bind
        source: /vagrant/github_actions_test/coverage
        target: /github_actions_test/coverage