name: CI github_actions_test

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Setup requirements
        run: pip3 install -r requirements.txt
      - 
        name: Test
        run: coverage run -m pytest
      - 
        name: Coverage
        run: coverage html

