name: Python attendance app

on: [pull_request]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Cloning project
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          coverage run -m pytest
      - name: Coverage
        run: |
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/index.html
      - name: Docker Compose Building
        run: | 
          docker compose build
          docker compose ps -a
      - name: Docker Compose Running Test
        run: |
          docker compose run team-attendance-app -o 1 -m general -sd 2022-09-10 -ed 2022-09-20